// ==UserScript==
// @name         #InstanceTicker (Type-0) user.js 
// @namespace    https://github.com/fedpla/InstanceTicker/
// @version      201907052340
// @description  #InstanceTicker とは、Mastodon タイムライン上の投稿者のみなさんに所属インスタンス名を彩るカスタムCSSです。
// @author       weep https://weep.me/@weep
// @license      Original CSS © https://github.com/kyori1954 and #InstanceTicker © 2018 https://github.com/weepjp Released under the MIT license https://opensource.org/licenses/MIT
// @icon         data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABG0lEQVQ4y6WTLWzCUBSFnwAxxMQEE5uYQMxMDIGYmamEjvCX2lVM0ASxpCOBZE1mSINA1CCqq6ura6urq6urz3oeKEiBPF7y2S/v3HuuCMMQURRJ4jhGkiSSNE2RZZkkz3NJURQ4fCIIAtQnWzQmHm7HG9yN1mgOV3gY/uFp4KDVX+K5P8fLxzfa+gyd3hRv3S+8dz93At/3USsFN+MDwYCC31KwKAU/UvBaJagrChhJeJ53ncB13TOCZaWAgxWO4xwJ7s8JejsBN3SVgKsWtm0rR5ACy7KUh8jCCdM0lSOwuRcIqn/A+gvDMC6YwbxaoOu6cpV5iELTtOMIoxUeTx3TfgY8RCkg/AlhJM6FcENcM2Ff2FrC+vOGyD8Yvit5VS8OawAAAABJRU5ErkJggg==
//
// @match        https://tl.telmina.com/*
// @match        https://itabashi.0j0.jp/*
// @match        https://social.0ko.me/*
// @match        https://don.8mitsu.net/*
// @match        https://9177xe.tokyo/*
// @match        https://mstdn.a-tak.com/*
// @match        https://abyss.fun/*
// @match        https://testingmstdn.abcang.net/*
// @match        https://flower.afn.social/*
// @match        https://akanechan.love/*
// @match        https://hige.alterna-cloud.com/*
// @match        https://amemiya.work/*
// @match        https://angraecumnote.net/*
// @match        https://amefur.asia/*
// @match        https://aqours.run/*
// @match        https://m.aqr.af/*
// @match        https://delusion.ariela.jp/*
// @match        https://social.arnip.org/*
// @match        https://ding-dong.asmodeus.tokyo/*
// @match        https://mstdn.asterism.xyz/*
// @match        https://mstdn.atcurio.com/*
// @match        https://m.auri.ga/*
// @match        https://mstdn.b-shock.org/*
// @match        https://babymetal.party/*
// @match        https://babuu.club/*
// @match        https://mstdn.barippi.com/*
// @match        https://best-friends.chat/*
// @match        https://mstdn.binfish.jp/*
// @match        https://mastodon.bitbank.cc/*
// @match        https://blessedgeeks.org/*
// @match        https://biwakodon.com/*
// @match        https://social.bluecore.net/*
// @match        https://boiskokoro.club/*
// @match        https://bookwor.ms/*
// @match        https://botdon.net/*
// @match        https://mstdn.boxp.tk/*
// @match        https://d.c-cha.cc/*
// @match        https://mastodon.cardina1.red/*
// @match        https://catdon.life/*
// @match        https://catgram.jp/*
// @match        https://kero.ccsakura.jp/*
// @match        https://jitakurack.chotto.moe/*
// @match        https://mastodon.chotto.moe/*
// @match        https://cironnup.com/*
// @match        https://claris.cf/*
// @match        https://claristdon.net/*
// @match        https://comm.cx/*
// @match        https://gs.comm.cx/*
// @match        https://pl.comm.cx/*
// @match        https://mstdn.cosplayer.com/*
// @match        https://cpper.xyz/*
// @match        https://mastodon.crazynewworld.net/*
// @match        https://mstdn.cuezakuisgodofthe.world/*
// @match        https://cute2d.xyz/*
// @match        https://cutls.com/*
// @match        https://darui.work/*
// @match        https://mstdn.dasoran.net/*
// @match        https://deny.club/*
// @match        https://mstdn.dgm.pw/*
// @match        https://digineko.jp/*
// @match        https://mastodon.diglateam3.com/*
// @match        https://djanzu.tokyo/*
// @match        https://doll.social/*
// @match        https://dotdon.jp/*
// @match        https://svrdn.drillion.net/*
// @match        https://dtp-mstdn.jp/*
// @match        https://social.edge4cube.work/*
// @match        https://don.ebifly.xyz/*
// @match        https://eletusk.club/*
// @match        https://pm.ernix.jp/*
// @match        https://ertona.net/*
// @match        https://m.eula.dev/*
// @match        https://mstdn.f72u.net/*
// @match        https://felesitas.cloud/*
// @match        https://fetishdon.tk/*
// @match        https://ffxiv-mastodon.com/*
// @match        https://ifrit.gaia.ff14-mstdn.xyz/*
// @match        https://fla.red/*
// @match        https://ma.fono.jp/*
// @match        https://foresdon.jp/*
// @match        https://mstdn.fujii-yuji.net/*
// @match        https://mstdn.fukuoka.jp/*
// @match        https://mstdn.futaba-works.com/*
// @match        https://mstdn.fuyumori.net/*
// @match        https://gamelinks007.net/*
// @match        https://garakuta.online/*
// @match        https://gensokyo.town/*
// @match        https://md.ggtea.org/*
// @match        https://gingadon.com/*
// @match        https://mstdn.glorificatio.org/*
// @match        https://gnosia.info/*
// @match        https://gochisou.photo/*
// @match        https://don.gomasy.jp/*
// @match        https://gorone.xyz/*
// @match        https://mini.gorone.xyz/*
// @match        https://mstdn.gtn-works.com/*
// @match        https://mstdn.h3z.jp/*
// @match        https://social.mikutter.hachune.net/*
// @match        https://hakomas.cf/*
// @match        https://hakorena.net/*
// @match        https://handon.club/*
// @match        https://mstdn.haun.jp/*
// @match        https://hearthtodon.com/*
// @match        https://heislandmine.work/*
// @match        https://hexadon.net/*
// @match        https://hiruandon.life/*
// @match        https://social.hideo54.com/*
// @match        https://mdn.hinaloe.net/*
// @match        https://mstdn.hokkaido.jp/*
// @match        https://hokutodon.co/*
// @match        https://homoo.social/*
// @match        https://chaosphere.hostdon.jp/*
// @match        https://mstdn.hostdon.jp/*
// @match        https://mstdn.ht164.jp/*
// @match        https://mstdn.hyogo.jp/*
// @match        https://ichiji.social/*
// @match        https://iguanodon.net/*
// @match        https://mstdn.ijs01140.com/*
// @match        https://social.ikata.co/*
// @match        https://mstdn.ikebuku.ro/*
// @match        https://illuster.org/*
// @match        https://imastodon.net/*
// @match        https://mstdn.imoimo.xyz/*
// @match        https://mstdn.inct-densan.club/*
// @match        https://gadget.inpocket.net/*
// @match        https://isidai.com/*
// @match        https://iwatedon.net/*
// @match        https://grain.izayoiwind.net/*
// @match        https://mastodon.juggler.jp/*
// @match        https://junkhub.org/*
// @match        https://justodon.net/*
// @match        https://mstdn.kanagu.info/*
// @match        https://kancolle.social/*
// @match        https://chibi.kemo.no/*
// @match        https://mofu.kemo.no/*
// @match        https://kemoner-don.tokyo/*
// @match        https://mstdn.kemono-friends.info/*
// @match        https://kemonodon.club/*
// @match        https://kemoshi.co/*
// @match        https://mstdn.kessai-otaku.club/*
// @match        https://now.kibousoft.co.jp/*
// @match        https://social.kimamass.com/*
// @match        https://kirishima.cloud/*
// @match        https://kiritan.work/*
// @match        https://mn.kitetu.com/*
// @match        https://mstdn.klamath.jp/*
// @match        https://knzk.me/*
// @match        https://h.kokuda.org/*
// @match        https://kurage.cc/*
// @match        https://mstdn.kuriuzu.tk/*
// @match        https://mstdn.kurosuke.org/*
// @match        https://s2.libera.blue/*
// @match        https://mastodon.lithium03.info/*
// @match        https://toot.loner.jp/*
// @match        https://shikokudon.m.to/*
// @match        https://tebukuro.m.to/*
// @match        https://tokotodon.m.to/*
// @match        https://wasaradan.m.to/*
// @match        https://don.m2hq.net/*
// @match        https://machida.yokohama/*
// @match        https://maho.app/*
// @match        https://makimaki.jp/*
// @match        https://don.mamemo.online/*
// @match        https://raspidon.mamemo.online/*
// @match        https://manhole.club/*
// @match        https://tekkadon.manimani.cc/*
// @match        https://mast.moe/*
// @match        https://mastadon.jp/*
// @match        https://k-shiigi-136.masto.host/*
// @match        https://okadon.masto.host/*
// @match        https://porkmeeting.masto.host/*
// @match        https://wndp.masto.host/*
// @match        https://zhenya.masto.host/*
// @match        https://mastoden.com/*
// @match        https://mastodol.jp/*
// @match        https://mastodon-train.info/*
// @match        https://mastodon.kitchen/*
// @match        https://mastodon.to/*
// @match        https://mastodon.yokohama/*
// @match        https://mastodooooooon.xyz/*
// @match        https://mastodos.com/*
// @match        https://animal-crossing.mastportal.info/*
// @match        https://azurlane.mastportal.info/*
// @match        https://osomatsu.mastportal.info/*
// @match        https://pokemon.mastportal.info/*
// @match        https://mastodon.matcha-soft.com/*
// @match        https://mathtod.online/*
// @match        https://matitodon.com/*
// @match        https://mstdn.maud.io/*
// @match        https://melilot.icu/*
// @match        https://meganekeesu.tokyo/*
// @match        https://mental.social/*
// @match        https://obitsudon.midyuki.net/*
// @match        https://mikado-city.jp/*
// @match        https://mikumikudance.cloud/*
// @match        https://mstdn.mimikun.jp/*
// @match        https://mimumedon.com/*
// @match        https://mstdn.mini4wd-engineer.com/*
// @match        https://minohdon.jp/*
// @match        https://mstdn.misosi.ru/*
// @match        https://mstdn.miyazaki.jp/*
// @match        https://mochiwasadon.com/*
// @match        https://mstdn.moe-max.jp/*
// @match        https://mostodon.cloud/*
// @match        https://mosw.work/*
// @match        https://mastodon.motcha.tech/*
// @match        https://mstdn-amadeus.tech/*
// @match        https://mstdn-bike.net/*
// @match        https://mstdn-jp.site/*
// @match        https://mstdn-kanazawa.jp/*
// @match        https://mstdn-workers.com/*
// @match        https://mstdn.beer/*
// @match        https://mstdn.blue/*
// @match        https://mstdn.cc/*
// @match        https://gamecreate.mstdn.cloud/*
// @match        https://socialgame.mstdn.cloud/*
// @match        https://tablegame.mstdn.cloud/*
// @match        https://mstdn.fm/*
// @match        https://mstdn.guru/*
// @match        https://mstdn.jp/*
// @match        https://mstdn.love/*
// @match        https://mstdn.osaka/*
// @match        https://mstdn.tokyo/*
// @match        https://mstdn.vodka/*
// @match        https://nt.mstdon.app/*
// @match        https://rcj.mstdon.app/*
// @match        https://muknown.jp/*
// @match        https://mustardon.tokyo/*
// @match        https://ef67.myhome.cx/*
// @match        https://mstdn.mynoghra.jp/*
// @match        https://mzn-potatochips.me/*
// @match        https://nagoyadon.jp/*
// @match        https://www.nekotodon.com/*
// @match        https://nekotodon.com/*
// @match        https://mastodon.nara.jp/*
// @match        https://nayukana.info/*
// @match        https://mstdn.nekonote.cc/*
// @match        https://mstdn.nere9.help/*
// @match        https://don.neso.tech/*
// @match        https://netstat.app/*
// @match        https://mstdn.nil.nu/*
// @match        https://nitiasa.com/*
// @match        https://www.njp.asia/*
// @match        https://mastodon.noraworld.jp/*
// @match        https://v2.nyoki.club/*
// @match        https://don.nzws.me/*
// @match        https://md.objektiv2.net/*
// @match        https://odakyu.app/*
// @match        https://mastodon.oita.jp/*
// @match        https://omochi.xyz/*
// @match        https://m6n.onsen.tech/*
// @match        https://oransns.com/*
// @match        https://orenoshiro.site/*
// @match        https://mastodon.osyakasyama.me/*
// @match        https://otogamer.me/*
// @match        https://otoya.space/*
// @match        https://mstdn.otyakai.xyz/*
// @match        https://pao.moe/*
// @match        https://md.paoon.social/*
// @match        https://music.pawoo.net/*
// @match        https://pawoo.net/*
// @match        https://pcgamer.social/*
// @match        https://pekepeke.work/*
// @match        https://photodn.net/*
// @match        https://plasticmodels.tokyo/*
// @match        https://toot.playground.ws/*
// @match        https://mstdn.plusminus.io/*
// @match        https://plustodon.net/*
// @match        https://si.pmpm.pw/*
// @match        https://pomdon.top/*
// @match        https://mstdn.ponseta.ga/*
// @match        https://mastodon.potproject.net/*
// @match        https://mstdn.poyo.me/*
// @match        https://popon.pptdn.jp/*
// @match        https://mstdn.precure.fun/*
// @match        https://precure.ml/*
// @match        https://pso2.club/*
// @match        https://ro-mastodon.puyo.jp/*
// @match        https://qiitadon.com/*
// @match        https://qnmd.info/*
// @match        https://ika.queloud.net/*
// @match        https://rainyman.jp/*
// @match        https://raptol.net/*
// @match        https://real-escape.jp/*
// @match        https://toot.redmine.jp/*
// @match        https://mstdn.res.ac/*
// @match        https://mstdn.rinsuki.net/*
// @match        https://mstdn.ropo.jp/*
// @match        https://mstdn.ryanak.xyz/*
// @match        https://mstdn.ryecroft21.net/*
// @match        https://mstdn.sanin.link/*
// @match        https://mstdn.sasachi.tokyo/*
// @match        https://mstdn.schoolidol.club/*
// @match        https://seetake.net/*
// @match        https://setl.ist/*
// @match        https://ukadon.shillest.net/*
// @match        https://shimaidon.net/*
// @match        https://shiroganedon.net/*
// @match        https://sandbox.skoji.jp/*
// @match        https://mastodon.snowandtweet.jp/*
// @match        https://mstdn.soysoftware.net/*
// @match        https://mstdn.square-rooty.org/*
// @match        https://steam-don.fun/*
// @match        https://stellaria.network/*
// @match        https://sukebeneko.com/*
// @match        https://syasai.club/*
// @match        https://syosetu.social/*
// @match        https://hack.syscaller.jp/*
// @match        https://mastodon.tackman.info/*
// @match        https://mstdn.taiyaki.online/*
// @match        https://mstdn.tamag.org/*
// @match        https://taruntarun.net/*
// @match        https://tebukuro.pw/*
// @match        https://tegedon.net/*
// @match        https://one.telmina.com/*
// @match        https://terusid.com/*
// @match        https://social.timespiral.co.jp/*
// @match        https://mastodon.tmp1024.com/*
// @match        https://mstdn.toad-in-the-hole.net/*
// @match        https://mstd.toco2.fun/*
// @match        https://tokamstdn.jp/*
// @match        https://mstdn.tokyocameraclub.com/*
// @match        https://mstdn.tomokiwakimoto.com/*
// @match        https://toot.blue/*
// @match        https://tooting.ai/*
// @match        https://tsuki.network/*
// @match        https://sin.tyaku.com/*
// @match        https://mastodon.umikaki.net/*
// @match        https://mstdn.unasuke.com/*
// @match        https://under-bank.blue/*
// @match        https://mstdn.unigiri.net/*
// @match        https://unnerv.jp/*
// @match        https://m.upsilo.net/*
// @match        https://utodon.jp/*
// @match        https://v1x3n.net/*
// @match        https://vapers.jp/*
// @match        https://vmrpc.net/*
// @match        https://vocalodon.net/*
// @match        https://wakakyu.tk/*
// @match        https://waraiotoko.net/*
// @match        https://wlw.pw/*
// @match        https://wug.fun/*
// @match        https://mstdn.xn--h1ahnbk7d.xn--p1ai/*
// @match        https://xn--zck4ad5f2e.jp/*
// @match        https://md.xps2.net/*
// @match        https://mstdn.y-zu.org/*
// @match        https://mstdn.yakitamago.info/*
// @match        https://yakumo.foundation/*
// @match        https://mastodon.yamaken.jp/*
// @match        https://mstdn.ybk28.net/*
// @match        https://mstdn.yjsnpi.nu/*
// @match        https://ykzts.technology/*
// @match        https://yukari.cafe/*
// @match        https://toot.yukimochi.jp/*
// @match        https://yysk.icu/*
// @match        https://zaisu-club.xyz/*
// @match        https://mastodon.zunda.ninja/*
// @match        https://4eva.online/*
// @match        https://ramses.amicidelbaretto.org/*
// @match        https://animeisgay.com/*
// @match        https://appdot.net/*
// @match        https://aus.social/*
// @match        https://ausglam.space/*
// @match        https://social.avareborn.de/*
// @match        https://awooo.club/*
// @match        https://banana.dog/*
// @match        https://bangdream.space/*
// @match        https://mastodon.barkshark.tk/*
// @match        https://beach.city/*
// @match        https://bibeogaem.zone/*
// @match        https://mastodon.bida.im/*
// @match        https://birdsite.link/*
// @match        https://botsin.space/*
// @match        https://bsd.network/*
// @match        https://chat.cdstm.ch/*
// @match        https://chaos.social/*
// @match        https://chitter.xyz/*
// @match        https://cmx.im/*
// @match        https://comicscamp.club/*
// @match        https://computerfairi.es/*
// @match        https://cryptids.online/*
// @match        https://cybre.space/*
// @match        https://a.daizhige.org/*
// @match        https://mao.daizhige.org/*
// @match        https://mast.datamol.org/*
// @match        https://deadinsi.de/*
// @match        https://diaspodon.fr/*
// @match        https://die-partei.social/*
// @match        https://masto.donte.com.br/*
// @match        https://donphan.social/*
// @match        https://social.dropbear.xyz/*
// @match        https://miaou.drycat.fr/*
// @match        https://ehjovan.com/*
// @match        https://eldritch.cafe/*
// @match        https://elekk.xyz/*
// @match        https://emacsen.net/*
// @match        https://mstdn.ernix.jp/*
// @match        https://equestria.social/*
// @match        https://mast.eu.org/*
// @match        https://fellies.social/*
// @match        https://fosstodon.org/*
// @match        https://framapiaf.org/*
// @match        https://freedom.horse/*
// @match        https://freeradical.zone/*
// @match        https://futuregadgetlab.cc/*
// @match        https://g0v.social/*
// @match        https://gensokyo.social/*
// @match        https://glaceon.social/*
// @match        https://gameliberty.club/*
// @match        https://ephemeral.glitch.social/*
// @match        https://glitch.social/*
// @match        https://goblin.camp/*
// @match        https://godforsaken.website/*
// @match        https://the.goofs.space/*
// @match        https://gwomp.com/*
// @match        https://mastodon.gougere.fr/*
// @match        https://hellsite.site/*
// @match        https://social.homunyan.com/*
// @match        https://hostux.social/*
// @match        https://humblr.social/*
// @match        https://soc.ialis.me/*
// @match        https://icosahedron.website/*
// @match        https://social.imirhil.fr/*
// @match        https://infosec.exchange/*
// @match        https://tooting.intensifi.es/*
// @match        https://social.jesuislibre.net/*
// @match        https://jorts.horse/*
// @match        https://mastodon.ketchupma.io/*
// @match        https://kirakiratter.com/*
// @match        https://kitty.town/*
// @match        https://kosmos.social/*
// @match        https://layer8.space/*
// @match        https://lgbt.io/*
// @match        https://lgbtq.cool/*
// @match        https://liberdon.com/*
// @match        https://libertalia.world/*
// @match        https://social.linux.pizza/*
// @match        https://mastodon.lubar.me/*
// @match        https://mamot.fr/*
// @match        https://mastd.racing/*
// @match        https://producers.masto.host/*
// @match        https://masto.pt/*
// @match        https://mastodon.art/*
// @match        https://mastodon.at/*
// @match        https://mastodon.cloud/*
// @match        https://mastodon.club/*
// @match        https://mastodon.eus/*
// @match        https://mastodon.host/*
// @match        https://mastodon.social/*
// @match        https://mastodon.technology/*
// @match        https://mastodon.uno/*
// @match        https://mastodon.xyz/*
// @match        https://meemu.org/*
// @match        https://monads.online/*
// @match        https://moytura.org/*
// @match        https://mstdn.io/*
// @match        https://mstdn.mx/*
// @match        https://es.muy.moe/*
// @match        https://nebula.moe/*
// @match        https://newsbots.eu/*
// @match        https://niu.moe/*
// @match        https://noagendasocial.com/*
// @match        https://norden.social/*
// @match        https://notbird.site/*
// @match        https://nulled.red/*
// @match        https://occult.camp/*
// @match        https://octodon.social/*
// @match        https://social.okaris.de/*
// @match        https://onster.farm/*
// @match        https://en.osm.town/*
// @match        https://mastodon.papey.fr/*
// @match        https://phpc.social/*
// @match        https://piss.restaurant/*
// @match        https://playvicious.social/*
// @match        https://plush.city/*
// @match        https://pokemon.men/*
// @match        https://pony.social/*
// @match        https://qaf.men/*
// @match        https://qoto.org/*
// @match        https://queer.party/*
// @match        https://quey.org/*
// @match        https://social.quodverum.com/*
// @match        https://radical.town/*
// @match        https://raggedfeathers.com/*
// @match        https://toot-lab.reclaim.technology/*
// @match        https://mastodon.sdf.org/*
// @match        https://shelter.moe/*
// @match        https://sinblr.com/*
// @match        https://shpposter.club/*
// @match        https://skaia.space/*
// @match        https://mastodon.sleeping.town/*
// @match        https://sleeping.town/*
// @match        https://snouts.online/*
// @match        https://social.coop/*
// @match        https://sonomu.club/*
// @match        https://sunbeam.city/*
// @match        https://switter.at/*
// @match        https://takeoverthe.world/*
// @match        https://social.taker.fr/*
// @match        https://social.targaryen.house/*
// @match        https://social.tchncs.de/*
// @match        https://mastodon.tetaneutral.net/*
// @match        https://thraeryn.net/*
// @match        https://todon.nl/*
// @match        https://toot.berlin/*
// @match        https://toot.cafe/*
// @match        https://toot.cat/*
// @match        https://toot.site/*
// @match        https://tootplanet.space/*
// @match        https://trollian.space/*
// @match        https://twingyeo.kr/*
// @match        https://twinja.club/*
// @match        https://hellsite.tyronesama.moe/*
// @match        https://ubuntu.social/*
// @match        https://uelfte.club/*
// @match        https://social.unextro.net/*
// @match        https://uwu.social/*
// @match        https://vulpine.club/*
// @match        https://wake.st/*
// @match        https://wandering.shop/*
// @match        https://whomst.dog/*
// @match        https://witchcraft.cafe/*
// @match        https://witches.live/*
// @match        https://wp-social.net/*
// @match        https://wokka.be/*
// @match        https://social.wxcafe.net/*
// @match        https://wxw.moe/*
// @match        https://x0f.org/*
// @match        https://yiff.life/*
// @match        https://twista.283.cloud/*
// @match        https://misskey.barippi.com/*
// @match        https://gyutte.site/*
// @match        https://msk.kirigakure.net/*
// @match        https://kig.life/*
// @match        https://mi.makotia.me/*
// @match        https://misskey.m544.net/*
// @match        https://mewl.me/*
// @match        https://mi-chan.work/*
// @match        https://misskey.dev/*
// @match        https://misskey.io/*
// @match        https://misskey.love/*
// @match        https://twista.283.cloud/*
// @match        https://misskey.nana.sh/*
// @match        https://misskey.ranranhome.info/*
// @match        https://msky.naru.cafe/*
// @match        https://noir.pub/*
// @match        https://misskey.nokotaro.com/*
// @match        https://tri.cash/*
// @match        https://uhouho.xyz/*
// @match        https://xn--6r8h.tk/*
// @match        https://misskey.xps2.net/*
// @match        https://yuzulia.xyz/*
//
// @resource     CCSS https://raw.githubusercontent.com/fedpla/InstanceTicker/master/InstanceTicker.css
// @grant        GM_addStyle
// @grant        GM_getResourceText
//
//
/****************************************************
 * InstanceTicker.user.js                          *
 * https://github.com/fedpla/InstanceTicker         *
 ****************************************************/
//
//
// ==/UserScript==
// ここに処理を記載する
(function(){


     GM_addStyle(GM_getResourceText('CCSS'));


})();

